// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdixKvz2H7fqJYhE8jGpKRvu_IQbj5Mk',
    appId: '1:673345665331:web:bdc627acc5476002d16646',
    messagingSenderId: '673345665331',
    projectId: 'flutter-firebase-app-a5965',
    authDomain: 'flutter-firebase-app-a5965.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-a5965.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-wioH6GPVNs37Kz6lKezuQimypOgL3Xs',
    appId: '1:673345665331:android:ca8d5d24d18e212bd16646',
    messagingSenderId: '673345665331',
    projectId: 'flutter-firebase-app-a5965',
    storageBucket: 'flutter-firebase-app-a5965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABQmw07m8qFPTBGSPSwugrtC72vWhDCk8',
    appId: '1:673345665331:ios:e95bf3a7dbc006e8d16646',
    messagingSenderId: '673345665331',
    projectId: 'flutter-firebase-app-a5965',
    storageBucket: 'flutter-firebase-app-a5965.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABQmw07m8qFPTBGSPSwugrtC72vWhDCk8',
    appId: '1:673345665331:ios:a5a17ea6eba654e6d16646',
    messagingSenderId: '673345665331',
    projectId: 'flutter-firebase-app-a5965',
    storageBucket: 'flutter-firebase-app-a5965.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
